from .abi import abi_capabilities, abi_version
from .core import Controller, Motor
from .cyberbeast_endpoints import (
    CYBERBEAST_ENDPOINTS,
    DescriptorEntry,
    EP_AXIS_CAN_HEARTBEAT_RATE_MS,
    EP_AXIS_CAN_IS_EXTENDED,
    EP_AXIS_CAN_NODE_ID,
    EP_AXIS_CURRENT_STATE,
    EP_AXIS_ENABLE_WATCHDOG,
    EP_AXIS_REQUESTED_STATE,
    EP_AXIS_WATCHDOG_TIMEOUT,
    EP_CAN_AUTO_BUS_OFF,
    EP_CAN_AUTO_RETRANSMISSION,
    EP_CAN_BAUD_RATE,
    EP_CAN_BREAK_TIMEOUT,
    EP_CAN_ERROR,
    EP_CAN_PROTOCOL,
    EP_CONTROLLER_CONTROL_MODE,
    EP_CONTROLLER_INPUT_MODE,
    EP_CONTROLLER_POS_GAIN,
    EP_CONTROLLER_VEL_GAIN,
    EP_CONTROLLER_VEL_LIMIT,
    EP_ENCODER_CPR,
    EP_MIT_MAX_KD,
    EP_MIT_MAX_KP,
    EP_MIT_MAX_POS,
    EP_MIT_MAX_TORQUE,
    EP_MIT_MAX_VEL,
    EP_MOTOR_CALIBRATION_CURRENT,
    EP_MOTOR_CURRENT_LIM,
    EP_MOTOR_EFFECTIVE_CURRENT_LIM,
    EP_MOTOR_GEAR_RATIO,
    EP_MOTOR_POLE_PAIRS,
    EP_MOTOR_TORQUE_CONSTANT,
    EP_MOTOR_TORQUE_LIM,
    EP_ODRV_ERROR,
    EP_ODRV_IBUS,
    EP_ODRV_SERIAL_NUMBER,
    EP_ODRV_VBUS_VOLTAGE,
    EndpointSpec,
    get_cyberbeast_endpoint,
    parse_endpoint_descriptor,
)
from .damiao_registers import (
    DAMIAO_HIGH_IMPACT_RIDS,
    DAMIAO_PROTECTION_RIDS,
    DAMIAO_RW_REGISTERS,
    MODE_FORCE_POS,
    MODE_MIT,
    MODE_POS_VEL,
    MODE_VEL,
    RID_CTRL_MODE,
    RID_ESC_ID,
    RID_KI_APR,
    RID_KI_ASR,
    RID_KP_APR,
    RID_KP_ASR,
    RID_MST_ID,
    RID_PMAX,
    RID_TMAX,
    RID_TIMEOUT,
    RID_VMAX,
    RegisterSpec,
    get_damiao_register_spec,
)
from .dm_device_runtime import ensure_dm_device_runtime
from .errors import AbiLoadError, CallError, MotorBridgeError
from .models import Mode, MotorState
from ._version import VERSION


def get_version() -> str:
    return VERSION


__version__ = get_version()

__all__ = [
    "__version__",
    "get_version",
    "abi_version",
    "abi_capabilities",
    "ensure_dm_device_runtime",
    "Controller",
    "Motor",
    "Mode",
    "MotorState",
    "RegisterSpec",
    "DAMIAO_RW_REGISTERS",
    "DAMIAO_HIGH_IMPACT_RIDS",
    "DAMIAO_PROTECTION_RIDS",
    "get_damiao_register_spec",
    "RID_CTRL_MODE",
    "RID_MST_ID",
    "RID_ESC_ID",
    "RID_TIMEOUT",
    "RID_PMAX",
    "RID_VMAX",
    "RID_TMAX",
    "RID_KP_ASR",
    "RID_KI_ASR",
    "RID_KP_APR",
    "RID_KI_APR",
    "MODE_MIT",
    "MODE_POS_VEL",
    "MODE_VEL",
    "MODE_FORCE_POS",
    "EndpointSpec",
    "DescriptorEntry",
    "CYBERBEAST_ENDPOINTS",
    "get_cyberbeast_endpoint",
    "parse_endpoint_descriptor",
    "EP_AXIS_CURRENT_STATE",
    "EP_AXIS_REQUESTED_STATE",
    "EP_AXIS_WATCHDOG_TIMEOUT",
    "EP_AXIS_ENABLE_WATCHDOG",
    "EP_AXIS_CAN_NODE_ID",
    "EP_AXIS_CAN_IS_EXTENDED",
    "EP_AXIS_CAN_HEARTBEAT_RATE_MS",
    "EP_ODRV_ERROR",
    "EP_ODRV_VBUS_VOLTAGE",
    "EP_ODRV_IBUS",
    "EP_ODRV_SERIAL_NUMBER",
    "EP_CAN_ERROR",
    "EP_CAN_BAUD_RATE",
    "EP_CAN_PROTOCOL",
    "EP_CAN_BREAK_TIMEOUT",
    "EP_CAN_AUTO_BUS_OFF",
    "EP_CAN_AUTO_RETRANSMISSION",
    "EP_MOTOR_EFFECTIVE_CURRENT_LIM",
    "EP_MOTOR_GEAR_RATIO",
    "EP_MOTOR_POLE_PAIRS",
    "EP_MOTOR_CALIBRATION_CURRENT",
    "EP_MOTOR_TORQUE_CONSTANT",
    "EP_MOTOR_CURRENT_LIM",
    "EP_MOTOR_TORQUE_LIM",
    "EP_CONTROLLER_CONTROL_MODE",
    "EP_CONTROLLER_INPUT_MODE",
    "EP_CONTROLLER_POS_GAIN",
    "EP_CONTROLLER_VEL_GAIN",
    "EP_CONTROLLER_VEL_LIMIT",
    "EP_MIT_MAX_POS",
    "EP_MIT_MAX_VEL",
    "EP_MIT_MAX_TORQUE",
    "EP_MIT_MAX_KP",
    "EP_MIT_MAX_KD",
    "EP_ENCODER_CPR",
    "MotorBridgeError",
    "AbiLoadError",
    "CallError",
]
